name: terragrunt-plan reusable
on:
  workflow_call:
    inputs: 
      environment: 
        description: deployment environment
        type: string
        required: true
      working-directory:
        description: "working directory"
        required: true
        type: string

jobs:
  eu-west-1:
    runs-on: [Linux, ntt, uk, self-hosted]
    container: 
      image: ghcr.io/lexisnexis-rba/tas/xg5-terraform/terragrunt:0.19.11
    permissions:
      packages: read
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with: 
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::485575125510:role/github-ADFS-TAS-XG5-Terraform
          role-session-name: XG5TERRAFORMGithubSession

      - name: terragrunt refresh/validate 
        id: validate
        run: |
          terragrunt refresh
          terragrunt validate
        working-directory: ${{ inputs.working-directory }}

      - name: terragrunt plan 
        id: plan
        run: |
          terragrunt plan --terragrunt-non-interactive -out $PWD/tf.plan 
          # terragrunt show -no-color $PWD/tf.plan | tee tfplan
          # PLAN=$(cat tfplan)
          # echo "PLAN<<EOF" >> $GITHUB_ENV
          # echo "$PLAN" >> $GITHUB_ENV
          # echo "EOF" >> $GITHUB_ENV   
        working-directory: ${{ inputs.working-directory }}
        
      
