name: Build
on:
  pull_request: 
concurrency: 
  group: build-${{ github.ref}}

jobs:
  build-ris-bussvcscustomercloud-prod:
    runs-on: [Linux, ntt, uk, self-hosted]
    permissions:
      packages: read
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps: 
      - name: checkout code
        uses: actions/checkout@v3

      - name: check file changes
        uses: LexisNexis-RBA/xg5-terraform/.github/actions/paths-filter@master
        id: changes
        with: 
          filters: |
            ctest: 
              - live/ris-bussvcscustomercloud-prod/us-east-2/ctest/**/*
              - live/*.hcl
              - modules/**/*
            dr: 
              - live/ris-bussvcscustomercloud-prod/us-east-2/dr/**/*
              - live/*.hcl
              - modules/**/*
            production: 
              - live/ris-bussvcscustomercloud-prod/us-east-2/production/**/*
              - live/*.hcl
              - modules/**/*
    outputs: 
      change_ctest: ${{ steps.changes.outputs.ctest }}
      change_dr: ${{ steps.changes.outputs.dr }}
      change_production: ${{ steps.changes.outputs.production }}
  build-dr:
    name: dr
    needs: build-ris-bussvcscustomercloud-prod
    if: ${{ needs.build-ris-bussvcscustomercloud-prod.outputs.change_dr == 'true' }}
    uses: LexisNexis-RBA/xg5-terraform/.github/workflows/build-action.yml@master
    with: 
      environment: 'dr'
      working-directory: 'live/ris-bussvcscustomercloud-prod/us-east-2/dr'
    secrets: inherit

  build-ctest:
    name: ctest
    needs: build-ris-bussvcscustomercloud-prod
    if: ${{ needs.build-ris-bussvcscustomercloud-prod.outputs.change_ctest == 'true' }}
    uses: LexisNexis-RBA/xg5-terraform/.github/workflows/build-action.yml@master
    with: 
      environment: 'ctest'
      working-directory: 'live/ris-bussvcscustomercloud-prod/us-east-2/ctest'
    secrets: inherit

  build-prod:
    name: production
    needs: build-ris-bussvcscustomercloud-prod
    if: ${{ needs.build-ris-bussvcscustomercloud-prod.outputs.change_production == 'true' }}
    uses: LexisNexis-RBA/xg5-terraform/.github/workflows/build-action.yml@master
    with: 
      environment: 'production'
      working-directory: 'live/ris-bussvcscustomercloud-prod/us-east-2/production'
    secrets: inherit
  
