environment 
build-ris-bussvcscustomercloud-prod/us-east-2/ctest:

ris-bussvcscustomercloud-prod/us-east-2/ctest:

build-ris-bussvcscustomercloud-prod/us-east-2/dr:

ris-bussvcscustomercloud-prod/us-east-2/dr:

build-ris-bussvcscustomercloud-prod/us-east-2/production:

ris-bussvcscustomercloud-prod/us-east-2/production:


type
build



deploy



build




deploy




build



deploy